server:
  port: 8090

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/chat_server
    username: chat
    password: chat1234
  flyway:
    url: jdbc:postgresql://localhost:5432/chat_server
    user: chat
    password: chat1234
